### ISSUE TITLE
How to to annotate a document automatically

### ISSUE THREAD

**Issue by niutyut** [doccano/auto-labeling-pipeline#1]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System:
*   Python Version:
*   Package Version:

**Comment by Hironsan** [comment]
This package is intended to be used from the inside of doccano. You shouldn't use this package directly.

Please look forward to integrating this to doccano.

**Comment by niutyut** [comment]
how to integrating this to doccano？is there a induction？

**Comment by niutyut** [comment]
for example：It's a Jane Eyre, it's a Jane Eyre, it's a Jane Eyre.。I set Jane Eyre's tag to Book。Set the labels manually once and let the platform tag them automatically the other two times.how to implement？

**Comment by Hironsan** [comment]
> how to integrating this to doccano？is there a induction？

No. I will implement the feature.
